/** @file
  OneCrypto Library provides unified cryptographic services

  Copyright (C) Microsoft Corporation. All rights reserved.
  SPDX-License-Identifier: BSD-2-Clause-Patent

**/

// __REPLACEMENT_TAG__ - Autogenerated contents go here.
